# badge-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: badge
  namespace: <your-namespace>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: badge
  template:
    metadata:
      labels:
        app: badge
    spec:
      containers:
      - name: badge
        image: <your-dockerhub-username>/cloud-explorer:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
        env:
        - name: SITE_ADDRESS
          value: ":80" # <-- don't change this!
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
